[35기 성바울] ADD : SignUpView
wecode-bootcamp-korea/35-1st-TURTLE-HOME-backend pull request #3
Opened 2022-07-20 04:53 UTC by bawoool

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 view 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- signupview class에 회원가입 API 구현
- email과 phone_number가 데이터베이스에 존재할경우 회원가입 불가 및 에러 반환
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- validation.py에 email과 password의 조건문과 정규식을 넣어줌으로써 코드의 효율성을 높임
- 정규식의 조건과 일치하지 않을경우 ValidationError반환
- bcrypt를 이용한 비밀번호 암호화
- 값을 입력하지 않을경우 KEYERROR반환
- 모든 조건과 일치 즉 회원가입이 정상적으로 완료될 경우 SUCCESS메시지 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- validation.py에 정규식조건을 저장해 두면서 코드를 효율적으로 사용할 수 있는 걸 알게 됨
- httpie를 이용해 직접 통신해 보면서 에러가 나오는 이유에 대해 좀 더 알게 됨

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-07-20 07:41 UTC, Kang-kyunghun requested changes

2022-07-20 07:41 UTC, Kang-kyunghun commented on requirements.txt
> +httpie==3.2.1
httpie는 어디에서 사용하나요?

아마 프로젝트 내에서는 안 사용 될 것 같은데 코멘트로 남겨주세요.

2022-07-20 07:41 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'MESSAGE' : 'EXISTENT_EMAIL'}, status=400)
key 부분은 주로 소문자를 사용합니다.
다른 부분들도 찾아서 수정해 주세요.
```suggestion
                return JsonResponse({'message' : 'EXISTENT_EMAIL'}, status=400)
```

2022-07-20 07:41 UTC, Kang-kyunghun commented on users/views.py
> +
import convention에 맞춰주세요.
```suggestion
import json
import re 

import bcrypt
from django.http            import JsonResponse
from django.views           import View
from django.core.exceptions import ValidationError

from .validation import email_check, password_check
from .models     import User

```

2022-07-20 07:42 UTC, bawoool commented on users/views.py
> +                return JsonResponse({'MESSAGE' : 'EXISTENT_EMAIL'}, status=400)
수정하겠습니다!

2022-07-20 07:42 UTC, bawoool commented on users/views.py
> +
수정하겠습니다!

2022-07-20 07:44 UTC, bawoool commented on requirements.txt
> +httpie==3.2.1
회원가입이나 로그인 api를 작성 후 정상적으로 잘 작동되는지 확인해 보고자 httpie를 이용해서 직접 통신을 할때 사용했습니다.

2022-07-20 07:54 UTC, bawoool commented on users/views.py
> +
수정하겠습니다!

2022-07-21 02:54 UTC, Kang-kyunghun commented
LGTM!

2022-07-21 02:54 UTC, merged